version: 1.3.0
services:
  - php:
      version: 7.3

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin

cde-databases:
  - testdb1
  - testmigratedb1

events:
  build:
    steps:
      - setup-env:
          type: script
          script:
            - pushd docroot
            - echo "hello"
            - composer install
            - mkdir -p sites/default/files
            - sed -i "s/SITEGROUP/${PIPELINE_CLOUD_SITE}/" ../settings.php
            - sed -i "s/DBROLE/$(echo $CDE_DATABASES | awk -F ',' '{print $1}')/" ../settings.php
            - cp ../settings.php ./sites/default
  post-deploy:
    steps:
      - deploy:
          script:
            - pipelines-deploy
            # Next step would be to install Drupal, but can't do this in pipelines.
            #- pushd docroot && /usr/local/bin/drush8 site-install --account-name='admin' --account-mail='foo@bar.com' --site-mail='foo@bar.com' --account-pass='randompass' --site-name='Drupal 8'
